### ISSUE TITLE
Conflict with "Epson ePOS SDK for Android"

### ISSUE THREAD

**Issue by Jacksotnik** [sumup/sumup-android-sdk#15] opened 2016-10-28 12:40 UTC
Hello. In my app i'm using Epson SDK for to print receipts by bluetooth printers. Till i start integrate SumUp sdk in my project everything worked fine. But after i'm adding this part of SumUp

```
compile('com.sumup:merchant-sdk:1.61.0@aar') {
    transitive = true
} 
```

everything which connected with Epson SDK(searching devices, printing something) is not working and app is freezing.

In log i have only one error message:
`E/UncaughtException: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-universal-image-loader-1.9.5_c8e34566bf68d5b51034fa0185be964c6b67450f-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-support-annotations-24.2.1_06b433c1f10c54a2e320b128e9c62c6e789c56c8-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-smc-6.6.0_76b9c8ff0cc8160d4b4f87d5c09c781141d009b6-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-otto-1.3.8_fac426806dada4c0221d57c9afe29644b82fbf2e-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-org.puredata.android-pd-core-1.0.1_f6559a3401c4d8935d8e97d32445b8ed75520d3a-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-okio-1.6.0_00ebdd1bb8c35eaf3f7c1574e4b5fecddead199f-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-okhttp-2.7.5_aed202b4eb81f84972bc22577a185b9671d48c16-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-logging-1.2_ce1a37730b85c9960d20cfd1db82c53c07c8c567-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-javax.inject-1_ace1769e3d1b66767a1f1c51037dd1896526710c-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-javawriter-2.1.2_68d0820dc2cca5cc76be4664de6e76517f387955-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-internal_impl-24.2.1_fef4add2dc336a27ce9fd7636abb4d53b60f8b28-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-internal_impl-24.2.1_e6301f8a80fb5b4898437593f20024ba5a975e26-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-internal_impl-24.2.1_5e839de5dd84a1005200524b3a28f0154936e96b-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-internal_impl-24.2.1_552b625aff97e95d067eba6fb63643960994b78e-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-internal_impl-24.2.1_1eb2c49d993c091a035c36b2e5b9f2de5a8adeec-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-icepick-3.2.0_a60498b9bd229c028e9cabac6c88358191238d84-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-gson-2.6.2_bd90b35fae5a5962a11f8bbf8d2441718576df5e-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-ePOSEasySelect_b4f19c4c0c2ebcdc6ae6d91ffb40f41632629043-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-ePOS2_49d3ac521a40d832918c9e6d225fa72d49815f65-classes.dex", dex file "/data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-de.iosphere.sumup.pinplus.manche`

**Comment by Jacksotnik** [comment] 2016-10-28 13:01
Also when i add SumUp sdk to my project i have huge build errors list. The same situation when i'm trying to build SumUp test application. But in result app is starting. Here is one of error:
```
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.sumup.merchant.CoreState$1) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class. 
```
I have this error for each SumUp unit.  And after this errors i have 2 another:
```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexIndexOverflowException: Cannot merge new index 67672 into a non-jumbo instruction!
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
```

Maybe conflict with Epson connected with it?

**Comment by ultrah** [comment] 2016-10-28 13:32
For the first issue, the epson and the SumUp SDK require the same dependency. You will need to exclude this dependency from either the SumUp SDK or the epson SDK.

You can get the dependency tree of your app with

`'./gradlew app:dependencies'`

Syntax for excluding a dependency:

```
compile('com.sumup:merchant-sdk:1.61.0@aar') {
    exclude group: 'com.android.support', module: 'support-v4' // This is just an example, you need to use the conflicting dependency here
    transitive = true
} 
```

For the second issue, you have reached the 64k method limit and need to use MultiDex:

https://developer.android.com/studio/build/multidex.html

**Comment by Jacksotnik** [comment] 2016-10-28 14:44
Sorry, can you please help me to fix it becuuse i never did it. I'm about dependencies. Hore is a list what i have after app:dependencies command. But i don't see anything connected with epson and SumUp
```
Information:Gradle tasks [app:dependencies]
Error:\--- com.android.support:support-v4:24.0.0 -> 24.2.1
Error:+--- com.android.support:support-compat:24.2.1
Error:|    \--- com.android.support:support-annotations:24.2.1
Error:+--- com.android.support:support-media-compat:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-utils:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-fragment:24.2.1
Error:+--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-media-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1 (*)
Error:\--- com.android.support:support-core-utils:24.2.1 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.android.gms:play-services-tasks:9.8.0 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.firebase:firebase-common:9.8.0 (*)
Error:\--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-v4:24.0.0 -> 24.2.1
Error:+--- com.android.support:support-compat:24.2.1
Error:|    \--- com.android.support:support-annotations:24.2.1
Error:+--- com.android.support:support-media-compat:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-utils:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-fragment:24.2.1
Error:+--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-media-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1 (*)
Error:\--- com.android.support:support-core-utils:24.2.1 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.android.gms:play-services-tasks:9.8.0 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.firebase:firebase-common:9.8.0 (*)
Error:\--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-v4:24.0.0 -> 24.2.1
Error:+--- com.android.support:support-compat:24.2.1
Error:|    \--- com.android.support:support-annotations:24.2.1
Error:+--- com.android.support:support-media-compat:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-utils:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-fragment:24.2.1
Error:+--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-media-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1 (*)
Error:\--- com.android.support:support-core-utils:24.2.1 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.android.gms:play-services-tasks:9.8.0 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.firebase:firebase-common:9.8.0 (*)
Error:\--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-v4:24.0.0 -> 24.2.1
Error:+--- com.android.support:support-compat:24.2.1
Error:|    \--- com.android.support:support-annotations:24.2.1
Error:+--- com.android.support:support-media-compat:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-utils:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-fragment:24.2.1
Error:+--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-media-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1 (*)
Error:\--- com.android.support:support-core-utils:24.2.1 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.android.gms:play-services-tasks:9.8.0 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.firebase:firebase-common:9.8.0 (*)
Error:\--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-v4:24.0.0 -> 24.2.1
Error:+--- com.android.support:support-compat:24.2.1
Error:|    \--- com.android.support:support-annotations:24.2.1
Error:+--- com.android.support:support-media-compat:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-utils:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1
Error:|    \--- com.android.support:support-compat:24.2.1 (*)
Error:\--- com.android.support:support-fragment:24.2.1
Error:+--- com.android.support:support-compat:24.2.1 (*)
Error:+--- com.android.support:support-media-compat:24.2.1 (*)
Error:+--- com.android.support:support-core-ui:24.2.1 (*)
Error:\--- com.android.support:support-core-utils:24.2.1 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.android.gms:play-services-tasks:9.8.0 (*)
Error:+--- com.google.android.gms:play-services-basement:9.8.0 (*)
Error:\--- com.google.firebase:firebase-common:9.8.0 (*)
Error:\--- com.android.support:support-compat:24.2.1 (*)
Information:BUILD SUCCESSFUL
Information:Total time: 0.499 secs
Information:95 errors
```

**Comment by ultrah** [comment] 2016-10-28 14:52
Are you running this in the root directory of your project? The output should be a lot larger

Maybe try removing the SumUp SDK dependency and try without it.

This is the dependency tree of the SumUp app:

````
com.sumup:merchant-sdk:1.61.0
+--- com.android.support:support-v4:23.4.0 
+--- com.android.support:appcompat-v7:23.4.0
+--- com.android.support:cardview-v7:23.4.0
+--- com.nostra13.universalimageloader:universal-image-loader:1.9.5
+--- com.sumup.android:logging:1.2
+--- com.squareup.okhttp:okhttp:2.7.5
|    \--- com.squareup.okio:okio:1.6.0
+--- com.squareup:otto:1.3.8
+--- net.sf.smc:smc:6.6.0
+--- com.google.code.gson:gson:2.6.2
+--- com.google.zxing:core:3.2.1
+--- de.keyboardsurfer.android.widget:crouton:1.8.5
+--- com.neenbedankt.bundles:argument:1.0.4
|    +--- com.squareup:javawriter:2.1.2
|    \--- com.neenbedankt.bundles:common:1.0.4
|         \--- com.squareup:javawriter:2.1.2
+--- frankiesardo:icepick:3.2.0
+--- com.squareup.dagger:dagger:1.2.2
|    \--- javax.inject:javax.inject:1
\--- com.sumup:readerlib:1.61.0
     +--- com.sumup.android:logging:1.2
     +--- de.iosphere.sumup.pinplus.manchesterlib:manchesterlib:1.1.5
     +--- com.squareup:otto:1.3.8
     +--- org.puredata.android:pd-core:1.0.1
     |    +--- com.android.support:support-v4:23.1.1 
     |    \--- com.noisepages.nettoyeur:midi:1.0.0-rc1
     \--- com.android.support:support-annotations:23.4.0 
````

**Comment by Jacksotnik** [comment] 2016-10-28 14:54
You mean try to remove one by one?

**Comment by Jacksotnik** [comment] 2016-10-28 14:56
I'm doing it so
![2016-10-28_17-56-03](https://cloud.githubusercontent.com/assets/23119861/19810894/deb54afa-9d37-11e6-9cc3-f8d8c9f1e466.jpg)

**Comment by ultrah** [comment] 2016-10-28 14:59
Try adding this to the sumup dependency: 

`exclude group: 'com.nostra13.universalimageloader', module: 'universal-image-loader'`

does it fix the issue?

**Comment by Jacksotnik** [comment] 2016-10-28 15:05
No, with this lina app is crashing on start

**Comment by Jacksotnik** [comment] 2016-10-28 15:06
In monday i will try to exclude one by one

**Comment by Jacksotnik** [comment] 2016-10-31 09:05
Hello again. Today from morning i have tried to exclude dependencies one by one, no any result. Every time the same error. Do you have any other ideas?

**Comment by ultrah** [comment] 2016-10-31 09:07
Please provide a sample application that reproduces the issue, then we will have a look and fix it.

**Comment by Jacksotnik** [comment] 2016-10-31 09:09
Ok i will prepare small application with this problem. Where should i upload it?

**Comment by ultrah** [comment] 2016-10-31 09:13
Just attach it to this issue please

**Comment by Jacksotnik** [comment] 2016-10-31 10:54
Here you can download test application 
[https://drive.google.com/open?id=0ByG8Xnf69VaWSHl5T1ppdFo5eFk](url)

For to catch error you have to press on "Discovery start" button.

**Comment by ultrah** [comment] 2016-10-31 12:34
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hssoft.sumupepsonconflictapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hssoft.sumupepsonconflictapp-1/lib/arm, /data/app/com.hssoft.sumupepsonconflictapp-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libepos2.so"`

To me this looks like a different issue than what you originally reported in this thread. Is this correct?

**Comment by Jacksotnik** [comment] 2016-10-31 12:38
No, problem the same. 
Here error what i have on my system:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.hssoft.sumupepsonconflictapp, PID: 14999
                  java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-universal-image-loader-1.9.5_c8e34566bf68d5b51034fa0185be964c6b67450f-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-support-annotations-24.2.1_06b433c1f10c54a2e320b128e9c62c6e789c56c8-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-smc-6.6.0_76b9c8ff0cc8160d4b4f87d5c09c781141d009b6-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-otto-1.3.8_fac426806dada4c0221d57c9afe29644b82fbf2e-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-org.puredata.android-pd-core-1.0.1_0b2ed110654fa92180e81aac3f3004db00adeb82-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-okio-1.6.0_00ebdd1bb8c35eaf3f7c1574e4b5fecddead199f-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-okhttp-2.7.5_aed202b4eb81f84972bc22577a185b9671d48c16-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-logging-1.2_ce1a37730b85c9960d20cfd1db82c53c07c8c567-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-javax.inject-1_ace1769e3d1b66767a1f1c51037dd1896526710c-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-javawriter-2.1.2_68d0820dc2cca5cc76be4664de6e76517f387955-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-internal_impl-24.2.1_bb0d1f0cfd985a1680cc2950b90263ba159830d7-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-internal_impl-24.2.1_ad8d397ff10e721e8c56d77c8eb94ed7c655e44b-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-internal_impl-24.2.1_7ad39726db79b8d2d3feb6cfc9f628d73b6323d0-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-internal_impl-24.2.1_6020b038d0b604aea2299a7d73006f98b6b1ed28-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-internal_impl-24.2.1_0047473687a0a70aa47c02bdbcc3ec7088354aaa-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-icepick-3.2.0_a60498b9bd229c028e9cabac6c88358191238d84-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-gson-2.6.2_bd90b35fae5a5962a11f8bbf8d2441718576df5e-classes.dex", dex file "/data/data/com.hssoft.sumupepsonconflictapp/files/instant-run/dex/slice-ePOSEasySelect_d2759002ac602099a80dace9c178c7a4e9e2fd84-classes.dex", dex file "/data/data/com.hssoft.sum
```

**Comment by ultrah** [comment] 2016-10-31 12:41
I can not reproduce this issue, but the crash can be fixed by adding this to `defaultConfig`:

```
ndk {
    abiFilters "armeabi"
}
```

**Comment by Jacksotnik** [comment] 2016-10-31 12:42
When you have crash? On app start or after press on button "Discovery start"?

**Comment by ultrah** [comment] 2016-10-31 12:43
On app start. Once I add these lines, everything is fine

**Comment by Jacksotnik** [comment] 2016-10-31 12:44
My issue is error after pressing on button. I think your crash on app start connected with testing on virtual device

**Comment by ultrah** [comment] 2016-10-31 12:44
No, I used a nexus 5 for testing. Clicking the button also does not result in a crash once these lines are added

**Comment by Jacksotnik** [comment] 2016-10-31 12:46
In your errom i'm seeing line "couldn't find "libepos2.so"" So i think Epson SDK is not loaded

**Comment by Jacksotnik** [comment] 2016-10-31 12:49
I't from Epson instruction. Can you please check if described files present in this forders?
![2016-10-31_14-48-20](https://cloud.githubusercontent.com/assets/23119861/19854698/1ce32c46-9f79-11e6-9506-50c6d4832375.jpg)

**Comment by Jacksotnik** [comment] 2016-10-31 12:50
![2016-10-31_14-50-02](https://cloud.githubusercontent.com/assets/23119861/19854752/56baacbe-9f79-11e6-86e0-3ec2b82c4202.jpg)

**Comment by ultrah** [comment] 2016-10-31 12:50
[Archive.zip](https://github.com/sumup/sumup-android-sdk/files/561748/Archive.zip)

This is with the fix included, I can not reproduce the issue anymore now.

**Comment by Jacksotnik** [comment] 2016-10-31 12:57
Did you enabled bluetooth on your device?

**Comment by ultrah** [comment] 2016-10-31 13:13
Yes, bluetooth was enabled. Does the crash still happen for you with the new version?

**Comment by Jacksotnik** [comment] 2016-10-31 13:25
No. This was helpfull
```
ndk {
    abiFilters "armeabi"
}
```
Thank's for your help :)

**Comment by ultrah** [comment] 2016-10-31 13:26
No problem.

**Closed by ultrah** 2016-10-31 13:26 UTC
